<?php

header('HTTP/1.1 503 Service Unavailable');
header('Retry-After: 900'); // 15 minutes in seconds

?><!DOCTYPE html><!-- "' --></script></style></noscript></xmp>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Chyba serveru</title>

<link href="https://fonts.googleapis.com/css?family=Libre+Baskerville&subset=latin-ext" rel="stylesheet">
<style>
	#error-body { font-size: 12pt; font-family: 'Libre Baskerville', serif; background: white; width: 480px; margin: 150px auto; padding: 10px 20px }
	#error-body h1 { background: none; color: #333; margin: .6em 0; line-height: 1.1; }
	#error-body p { background: none; color: #333; margin: 1.5em 0; text-align: justify; line-height: 1.5; }
	#error-body p.text-muted { color: #777; }
</style>

<div id="error-body">
	<h1>Probíhá údržba</h1>

	<p>
		Omlouváme se! Ale právě probíhá údržba. Vraťte se, prosím, později.
	</p>

	<p class="text-muted">DATOS - data o spravedlnosti, z.s., <a href="mailto:info@cestiadvokati.cz">info@cestiadvokati.cz</a>.</p>
</div>
